export const company = {
  name: "Hasanur Jaya Sdn Bhd",
  shortName: "Hasanur Jaya",
  tagline: "Construction & Development",
  description: "Premier construction and development company in Brunei, delivering quality, integrity, and innovation since 1995.",
  founded: 1995,
  yearsInBusiness: 28,
  phone: "+673 123 4567",
  email: "hanasur@gmail.com",
  address: "No 17, Spg 42, Jalan Batu Bersurat, Bandar Seri Begawan, Brunei",
  hours: "Mon - Sat 8AM - 5PM, Sunday - CLOSED",
  social: {
    facebook: "https://www.facebook.com/Hjayasdnbhd/",
    linkedin: "https://bn.linkedin.com/company/hasanur-jaya-sdn-bhd",
  },
  hero: {
    headline: "Building Brunei's Future Through Engineering Excellence",
    subheadline: "Delivering construction, infrastructure, renovation, engineering, and maintenance solutions with quality, integrity, and innovation.",
  },
  stats: [
    { label: "Projects Completed", value: 120, suffix: "+" },
    { label: "Employees", value: 200, suffix: "+" },
    { label: "Awards", value: 5, suffix: "" },
    { label: "Happy Clients", value: 100, suffix: "+" },
  ],
  about: {
    history: "Hasanur Jaya Sdn Bhd started with a simple vision: to redefine the construction landscape in Brunei through quality, integrity, and innovation. Over the last 28 years, we have grown from a small family business into one of the most respected construction firms in the region. Our journey has been marked by iconic projects, enduring relationships with our clients, and a relentless pursuit of excellence in every brick we lay and every beam we place.",
    mission: "To provide high-quality construction services with a focus on safety, sustainability, and client satisfaction, contributing to the nation's infrastructure development.",
    vision: "To be the premier choice for luxury residential and large-scale commercial projects, known for our architectural brilliance and engineering precision.",
    values: [
      { title: "Safety First", description: "We prioritize the safety of our workers and the public above all else, maintaining rigorous safety standards on every site." },
      { title: "Quality Focused", description: "We never compromise on materials or craftsmanship, ensuring every project stands the test of time." },
      { title: "Integrity", description: "Transparency and honesty are at the heart of our business. We build trust through our actions." },
      { title: "Innovation", description: "We embrace modern construction technologies and sustainable practices to deliver superior results." },
    ],
    leadership: [
      { name: "Haji Hassan", role: "Managing Director", title: "MANAGING DIRECTOR" },
      { name: "Dayang Siti", role: "Creative Director", title: "CREATIVE DIRECTOR" },
      { name: "Ahmad Jaya", role: "Technical Director", title: "TECHNICAL DIRECTOR" },
      { name: "Mohammad Ali", role: "Operations Director", title: "OPERATIONS DIRECTOR" },
    ],
    team: [
      { name: "John Doe", role: "Civil Engineer", title: "CIVIL ENGINEER" },
      { name: "Jane Smith", role: "Safety Officer", title: "SAFETY OFFICER" },
    ],
  },
  services: [
    {
      id: "general-construction",
      title: "General Construction",
      slug: "general-construction",
      shortDesc: "Custom-built residential and commercial properties tailored to your specific needs and lifestyle.",
      fullDesc: "We specialize in high-end villas, bespoke homes, and large-scale commercial developments. From foundation to finishing, our team delivers exceptional craftsmanship on every project. Our general construction services encompass everything from site preparation and foundation work through structural framing, MEP installations, interior finishes, and handover. We work closely with clients, architects, and engineers to ensure each project meets the highest standards of quality and design intent.",
      icon: "Building2",
      category: "Luxury Residential & Commercial",
      capabilities: [
        "Site Preparation & Earthworks",
        "Foundation & Structural Works",
        "Reinforced Concrete Structures",
        "Steel Structure Fabrication & Erection",
        "MEP (Mechanical, Electrical, Plumbing)",
        "Interior Fit-Out & Finishing",
        "Facade & Cladding Systems",
        "Landscaping & External Works",
      ],
    },
    {
      id: "architectural-design",
      title: "Architectural Design",
      slug: "architectural-design",
      shortDesc: "Innovative and functional architectural designs that blend aesthetics with structural integrity.",
      fullDesc: "Our design team creates innovative blueprints that maximize space and aesthetic appeal while ensuring structural integrity and cost-effectiveness. We combine creative vision with technical expertise to deliver architectural solutions that inspire. From conceptual design through detailed construction documents, our architects work collaboratively with clients to transform ideas into buildable realities.",
      icon: "Palette",
      category: "Design & Planning",
      capabilities: [
        "Conceptual Design & Feasibility Studies",
        "Space Planning & Layout Optimization",
        "3D Visualization & Rendering",
        "Building Information Modeling (BIM)",
        "Structural Engineering Design",
        "Construction Documentation",
        "Permitting & Regulatory Approvals",
        "Value Engineering",
      ],
    },
    {
      id: "project-management",
      title: "Project Management",
      slug: "project-management",
      shortDesc: "End-to-end management ensuring projects are completed on time, within budget, and to the highest standards.",
      fullDesc: "Rigorous management ensures every project phase meets our strict quality and safety criteria. Our experienced project managers oversee every aspect of construction, from initial planning and procurement through construction, commissioning, and handover. We employ industry-leading project control methodologies to track progress, manage risks, and ensure timely delivery within budget.",
      icon: "ClipboardCheck",
      category: "Professional Services",
      capabilities: [
        "Project Planning & Scheduling",
        "Cost Management & Budget Control",
        "Procurement & Supply Chain Management",
        "Risk Management & Mitigation",
        "Quality Assurance & Quality Control",
        "Contract Administration",
        "Stakeholder Communication",
        "Commissioning & Handover",
      ],
    },
    {
      id: "renovation-remodeling",
      title: "Renovation & Remodeling",
      slug: "renovation-remodeling",
      shortDesc: "Breathe new life into existing structures with our expert renovation and remodeling services.",
      fullDesc: "Long-term maintenance services to keep your property in pristine condition for years. Whether it's a complete building overhaul, interior modernization, or structural upgrading, our renovation team brings expertise and care to every project. We understand the unique challenges of working with existing structures and pride ourselves on delivering transformations that exceed expectations.",
      icon: "RefreshCw",
      category: "Building Enhancement",
      capabilities: [
        "Full Building Renovation",
        "Interior Remodeling & Modernization",
        "Structural Retrofitting & Strengthening",
        "Facade Restoration & Upgrades",
        "MEP System Upgrades",
        "Heritage & Conservation Works",
        "Space Reconfiguration",
        "Emergency Repair Services",
      ],
    },
    {
      id: "infrastructure-development",
      title: "Infrastructure Development",
      slug: "infrastructure-development",
      shortDesc: "Specialized in road works, drainage systems, and large-scale public infrastructure development.",
      fullDesc: "We have extensive experience in developing critical infrastructure that serves communities and drives economic growth. From roads and bridges to utilities and public facilities, our infrastructure division delivers projects that meet international standards for quality, safety, and durability.",
      icon: "Route",
      category: "Public & Civil Works",
      capabilities: [
        "Road & Highway Construction",
        "Drainage & Stormwater Management",
        "Water Supply & Distribution Systems",
        "Sewerage & Wastewater Treatment",
        "Bridge & Culvert Construction",
        "Utilities Relocation & Protection",
        "Earthworks & Land Reclamation",
        "Public Facilities Development",
      ],
    },
    {
      id: "green-building",
      title: "Green Building",
      slug: "green-building",
      shortDesc: "Eco-friendly construction practices and sustainable materials for a better tomorrow.",
      fullDesc: "Integrating green technologies and energy-efficient materials into every build. We are committed to sustainable construction practices that reduce environmental impact while enhancing building performance and occupant comfort. Our green building solutions help clients achieve certification standards while realizing long-term operational savings.",
      icon: "Leaf",
      category: "Sustainable Solutions",
      capabilities: [
        "Energy-Efficient Building Design",
        "Sustainable Material Selection",
        "Solar Panel & Renewable Energy Integration",
        "Rainwater Harvesting Systems",
        "Green Roof & Vertical Garden Systems",
        "Waste Management & Recycling",
        "Indoor Environmental Quality",
        "Green Building Certification (GBI/LEED)",
      ],
    },
  ],
  industries: [
    { name: "Government", description: "Public sector projects including administrative buildings, civil infrastructure, and community facilities.", icon: "Landmark" },
    { name: "Commercial", description: "Office towers, retail centers, hotels, and mixed-use commercial developments.", icon: "Building" },
    { name: "Residential", description: "Luxury villas, landed properties, and high-end residential communities.", icon: "Home" },
    { name: "Industrial", description: "Factories, warehouses, processing plants, and industrial facilities.", icon: "Factory" },
    { name: "Infrastructure", description: "Roads, bridges, drainage systems, and public utility infrastructure.", icon: "Route" },
    { name: "Hospitality", description: "Hotels, resorts, restaurants, and leisure facilities.", icon: "Hotel" },
    { name: "Education", description: "Schools, universities, training centers, and educational campuses.", icon: "GraduationCap" },
    { name: "Healthcare", description: "Hospitals, clinics, medical centers, and healthcare facilities.", icon: "HeartPulse" },
  ],
  products: [
    {
      name: "Hanchi Waterproofing",
      tagline: "Industrial-grade liquid membranes and sealants for complete moisture protection.",
      description: "Hanchi waterproofing solutions provide exceptional protection against water ingress for all types of structures. Our range includes liquid-applied membranes, cementitious coatings, and sealants suitable for roofs, basements, bathrooms, water tanks, and external walls.",
      applications: ["Roof Waterproofing", "Basement Waterproofing", "Bathroom & Wet Areas", "Water Tank Lining", "External Wall Coating", "Balcony & Terrace"],
      features: ["Excellent Adhesion", "UV Resistant", "Flexible & Crack-Bridging", "Easy Application", "Durable & Long-Lasting", "Environmentally Friendly"],
    },
    {
      name: "Hanchi Repair Solutions",
      tagline: "High-strength mortars and epoxy resins for reinforcing aging or damaged structures.",
      description: "Hanchi repair solutions are engineered for structural strengthening and restoration. Our high-performance mortars, epoxy resins, and protective coatings are designed to extend the service life of concrete and masonry structures.",
      applications: ["Concrete Crack Repair", "Structural Strengthening", "Spalling Repair", "Floor Hardening", "Anchor Grouting", "Protective Coating"],
      features: ["High Compressive Strength", "Low Shrinkage", "Excellent Bonding", "Fast Curing Options", "Freeze-Thaw Resistant", "Chemical Resistant"],
    },
  ],
  whyChooseUs: [
    { title: "Quality Craftsmanship", description: "Every project is executed with meticulous attention to detail and superior workmanship.", icon: "Award" },
    { title: "Expert Engineering", description: "Our team brings deep technical expertise and innovative solutions to every challenge.", icon: "Brain" },
    { title: "Timely Delivery", description: "We pride ourselves on completing projects on schedule without compromising quality.", icon: "Clock" },
    { title: "Sustainable Construction", description: "Committed to environmentally responsible building practices and materials.", icon: "Leaf" },
    { title: "Experienced Workforce", description: "Skilled professionals with years of experience across diverse project types.", icon: "Users" },
    { title: "Customer Satisfaction", description: "Building lasting relationships through transparency, communication, and results.", icon: "Heart" },
  ],
  safety: {
    commitment: "At Hasanur Jaya, safety is not just a policy — it's a core value that guides everything we do. We are committed to providing a safe and healthy working environment for all our employees, subcontractors, and the communities where we operate.",
    policies: [
      "Zero Harm Philosophy — every incident is preventable",
      "Strict compliance with Brunei's Workplace Safety and Health regulations",
      "Regular safety training and competency assessments for all personnel",
      "Comprehensive risk assessments before every project phase",
      "Continuous monitoring and improvement of safety performance",
    ],
    quality: "We maintain rigorous quality assurance processes throughout every project. Our quality management system ensures that all work meets or exceeds industry standards and client expectations.",
    environment: "We are dedicated to minimizing our environmental footprint through responsible resource management, waste reduction, and sustainable construction practices.",
  },
  projects: [
    { title: "Project 1", client: "Government of Brunei", location: "Bandar Seri Begawan", status: "Completed", description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.", scope: "Design & Build" },
    { title: "Project 2", client: "Private Developer", location: "Kuala Belait", status: "Completed", description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.", scope: "Main Contract" },
    { title: "Project 3", client: "Commercial Client", location: "Gadong", status: "Ongoing", description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.", scope: "Design & Build" },
    { title: "Project 4", client: "Government of Brunei", location: "Seria", status: "Completed", description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.", scope: "Infrastructure" },
    { title: "Project 5", client: "Private Client", location: "Bandar Seri Begawan", status: "Completed", description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.", scope: "Renovation" },
  ],
  gallery: [
    { src: "/images/gallery/img-1.jpg", alt: "Construction site", category: "Construction" },
    { src: "/images/gallery/img-2.jpg", alt: "Site progress", category: "Progress" },
    { src: "/images/gallery/img-3.jpg", alt: "Completed project", category: "Completed" },
    { src: "/images/gallery/img-4.jpg", alt: "Equipment", category: "Equipment" },
    { src: "/images/gallery/img-5.jpg", alt: "Workforce", category: "Workforce" },
    { src: "/images/gallery/img-6.jpg", alt: "Infrastructure", category: "Infrastructure" },
  ],
  navigation: [
    { label: "Home", href: "/" },
    { label: "About Us", href: "/about" },
    { label: "Services", href: "/services" },
    { label: "Projects", href: "/projects" },
    { label: "Industries", href: "/industries" },
    { label: "Products", href: "/products" },
    { label: "Safety & Quality", href: "/safety" },
    { label: "Gallery", href: "/gallery" },
    { label: "News", href: "/news" },
    { label: "Contact", href: "/contact" },
  ],
  careers: [
    {
      title: "Civil Engineer",
      type: "Full-Time",
      location: "Bandar Seri Begawan",
      department: "Engineering",
      description: "We are looking for an experienced Civil Engineer to join our project team.",
    },
    {
      title: "Safety Officer",
      type: "Full-Time",
      location: "Bandar Seri Begawan",
      department: "HSE",
      description: "Responsible for ensuring workplace safety compliance across all project sites.",
    },
    {
      title: "Project Manager",
      type: "Full-Time",
      location: "Bandar Seri Begawan",
      department: "Project Management",
      description: "Lead and manage construction projects from inception to completion.",
    },
  ],
};
