export const company = {
  name: "Hasanur Jaya Sdn Bhd",
  shortName: "Hasanur Jaya",
  tagline: "Construction & Engineering",
  description: "Premier construction, engineering, infrastructure, and facility maintenance company in Brunei Darussalam, delivering quality, integrity, and innovation since 1995.",
  founded: 1995,
  yearsInBusiness: 30,
  phone: "+673 123 4567",
  whatsapp: "+6731234567",
  email: "hanasur@gmail.com",
  address: "No 17, Spg 42, Jalan Batu Bersurat, Bandar Seri Begawan, Brunei",
  mapUrl: "https://www.google.com/maps/search/?api=1&query=Jalan+Batu+Bersurat+Bandar+Seri+Begawan+Brunei",
  hours: "Mon - Sat 8AM - 5PM, Sunday - CLOSED",
  website: "https://hasanurjaya.com",
  social: {
    facebook: "https://www.facebook.com/Hjayasdnbhd/",
    linkedin: "https://bn.linkedin.com/company/hasanur-jaya-sdn-bhd",
  },
  hero: {
    headline: "Building Brunei's Future with Engineering Excellence",
    subheadline: "Hasanur Jaya Sdn. Bhd. delivers high-quality construction, engineering, infrastructure, project management, and facility maintenance solutions across Brunei Darussalam.",
  },
  stats: [
    { label: "Projects Completed", value: 250, suffix: "+" },
    { label: "Years of Experience", value: 30, suffix: "+" },
    { label: "Professional Team", value: 200, suffix: "+" },
    { label: "Satisfied Clients", value: 180, suffix: "+" },
    { label: "Ongoing Projects", value: 15, suffix: "+" },
  ],
  about: {
    history: "Hasanur Jaya Sdn Bhd started with a simple vision: to redefine the construction landscape in Brunei through quality, integrity, and innovation. Over three decades, we have grown from a small family business into one of the most respected construction firms in the region — a trusted contractor for government agencies and private-sector clients alike. Our journey has been marked by iconic projects, enduring relationships with our clients, and a relentless pursuit of excellence in every brick we lay and every beam we place.",
    mission: "To provide high-quality construction services with a focus on safety, sustainability, and client satisfaction, contributing to the nation's infrastructure development.",
    vision: "To be the premier choice for luxury residential and large-scale commercial projects, known for our architectural brilliance and engineering precision.",
    values: [
      { title: "Safety First", description: "We prioritize the safety of our workers and the public above all else, maintaining rigorous safety standards on every site." },
      { title: "Quality Focused", description: "We never compromise on materials or craftsmanship, ensuring every project stands the test of time." },
      { title: "Integrity", description: "Transparency and honesty are at the heart of our business. We build trust through our actions." },
      { title: "Innovation", description: "We embrace modern construction technologies and sustainable practices to deliver superior results." },
    ],
    leadership: [
      { name: "Haji Hassan", role: "Managing Director", title: "MANAGING DIRECTOR" },
      { name: "Dayang Siti", role: "Creative Director", title: "CREATIVE DIRECTOR" },
      { name: "Ahmad Jaya", role: "Technical Director", title: "TECHNICAL DIRECTOR" },
      { name: "Mohammad Ali", role: "Operations Director", title: "OPERATIONS DIRECTOR" },
    ],
    team: [
      { name: "John Doe", role: "Civil Engineer", title: "CIVIL ENGINEER" },
      { name: "Jane Smith", role: "Safety Officer", title: "SAFETY OFFICER" },
    ],
  },
  services: [
    {
      id: "general-construction",
      title: "General Construction",
      slug: "general-construction",
      shortDesc: "Custom-built residential and commercial properties tailored to your specific needs and lifestyle.",
      fullDesc: "We specialize in high-end villas, bespoke homes, and large-scale commercial developments. From foundation to finishing, our team delivers exceptional craftsmanship on every project. Our general construction services encompass everything from site preparation and foundation work through structural framing, MEP installations, interior finishes, and handover. We work closely with clients, architects, and engineers to ensure each project meets the highest standards of quality and design intent.",
      icon: "Building2",
      image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1200&q=75",
      category: "Luxury Residential & Commercial",
      capabilities: [
        "Site Preparation & Earthworks",
        "Foundation & Structural Works",
        "Reinforced Concrete Structures",
        "Steel Structure Fabrication & Erection",
        "MEP (Mechanical, Electrical, Plumbing)",
        "Interior Fit-Out & Finishing",
        "Facade & Cladding Systems",
        "Landscaping & External Works",
      ],
    },
    {
      id: "civil-engineering",
      title: "Civil Engineering",
      slug: "civil-engineering",
      shortDesc: "Structural, geotechnical, and civil works engineered to international standards for public and private clients.",
      fullDesc: "Our civil engineering division delivers structural design, earthworks, foundations, and heavy civil works for government and private-sector projects across Brunei. We combine rigorous engineering analysis with practical construction expertise, ensuring every structure is safe, durable, and cost-effective from design through commissioning.",
      icon: "Compass",
      image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=75",
      category: "Engineering Services",
      capabilities: [
        "Structural Design & Analysis",
        "Geotechnical Investigation",
        "Earthworks & Land Development",
        "Deep & Shallow Foundations",
        "Retaining Structures",
        "Marine & Coastal Works",
        "Site Supervision & QA",
        "As-Built Documentation",
      ],
    },
    {
      id: "architectural-design",
      title: "Architectural Design",
      slug: "architectural-design",
      shortDesc: "Innovative and functional architectural designs that blend aesthetics with structural integrity.",
      fullDesc: "Our design team creates innovative blueprints that maximize space and aesthetic appeal while ensuring structural integrity and cost-effectiveness. We combine creative vision with technical expertise to deliver architectural solutions that inspire. From conceptual design through detailed construction documents, our architects work collaboratively with clients to transform ideas into buildable realities.",
      icon: "Palette",
      image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=75",
      category: "Design & Planning",
      capabilities: [
        "Conceptual Design & Feasibility Studies",
        "Space Planning & Layout Optimization",
        "3D Visualization & Rendering",
        "Building Information Modeling (BIM)",
        "Structural Engineering Design",
        "Construction Documentation",
        "Permitting & Regulatory Approvals",
        "Value Engineering",
      ],
    },
    {
      id: "mechanical-electrical",
      title: "Mechanical & Electrical",
      slug: "mechanical-electrical",
      shortDesc: "Complete M&E engineering — power, lighting, HVAC, plumbing, and building automation systems.",
      fullDesc: "Our M&E division designs, installs, tests, and commissions complete mechanical and electrical systems for buildings and industrial facilities. From low-voltage distribution and lighting to HVAC, fire protection, and building management systems, we deliver integrated services that keep facilities safe, efficient, and comfortable.",
      icon: "Zap",
      image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=1200&q=75",
      category: "Building Services",
      capabilities: [
        "Electrical Installation & Distribution",
        "HVAC Design & Installation",
        "Plumbing & Sanitary Systems",
        "Fire Protection & Alarm Systems",
        "Building Management Systems (BMS)",
        "Standby Power & Generators",
        "Testing & Commissioning",
        "Energy Efficiency Upgrades",
      ],
    },
    {
      id: "facility-maintenance",
      title: "Facility Maintenance",
      slug: "facility-maintenance",
      shortDesc: "Planned, preventive, and corrective maintenance keeping buildings and assets in peak condition.",
      fullDesc: "We provide comprehensive facility maintenance services for government buildings, commercial properties, and industrial facilities — from scheduled preventive maintenance and statutory inspections to 24/7 corrective response. Our maintenance operations are managed digitally through the HJSB EPPM platform, giving clients full visibility of work orders, assets, and service history.",
      icon: "Wrench",
      image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=1200&q=75",
      category: "Asset & Facility Services",
      capabilities: [
        "Preventive Maintenance Programs",
        "Corrective & Emergency Repairs",
        "Building Fabric Maintenance",
        "M&E Systems Servicing",
        "QR-Coded Asset Management",
        "Cleaning & Groundskeeping",
        "Statutory Inspections & Compliance",
        "24/7 Helpdesk & Work Orders",
      ],
    },
    {
      id: "project-management",
      title: "Project Management",
      slug: "project-management",
      shortDesc: "End-to-end management ensuring projects are completed on time, within budget, and to the highest standards.",
      fullDesc: "Rigorous management ensures every project phase meets our strict quality and safety criteria. Our experienced project managers oversee every aspect of construction, from initial planning and procurement through construction, commissioning, and handover. We employ industry-leading project control methodologies — powered by our HJSB EPPM platform — to track progress, manage risks, and ensure timely delivery within budget.",
      icon: "ClipboardCheck",
      image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=75",
      category: "Professional Services",
      capabilities: [
        "Project Planning & Scheduling",
        "Cost Management & Budget Control",
        "Procurement & Supply Chain Management",
        "Risk Management & Mitigation",
        "Quality Assurance & Quality Control",
        "Contract Administration",
        "Stakeholder Communication",
        "Commissioning & Handover",
      ],
    },
    {
      id: "steel-structure",
      title: "Steel Structure",
      slug: "steel-structure",
      shortDesc: "Fabrication and erection of structural steel for industrial, commercial, and infrastructure projects.",
      fullDesc: "From warehouses and factories to canopies and bridges, our steel structure team handles detailing, fabrication, surface treatment, delivery, and erection. We maintain strict welding and dimensional quality control, ensuring structures meet design loads and international fabrication standards.",
      icon: "Frame",
      image: "https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&w=1200&q=75",
      category: "Industrial & Structural",
      capabilities: [
        "Shop Drawings & Steel Detailing",
        "Structural Steel Fabrication",
        "Welding & NDT Quality Control",
        "Surface Preparation & Coating",
        "Site Erection & Bolting",
        "Roofing & Cladding Systems",
        "Mezzanines & Platforms",
        "Canopies & Skylights",
      ],
    },
    {
      id: "road-works-drainage",
      title: "Road Works & Drainage",
      slug: "road-works-drainage",
      shortDesc: "Roads, pavements, culverts, and stormwater drainage systems built for Brunei's tropical climate.",
      fullDesc: "We construct and rehabilitate roads, car parks, and drainage networks for public agencies and private developments. Our teams handle earthworks, sub-base and pavement layers, kerbing, road furniture, and complete stormwater management systems engineered for heavy tropical rainfall.",
      icon: "Route",
      image: "https://images.unsplash.com/photo-1508450859948-4e04fabaa4ea?auto=format&fit=crop&w=1200&q=75",
      category: "Public & Civil Works",
      capabilities: [
        "Road & Highway Construction",
        "Pavement Rehabilitation & Resurfacing",
        "Drainage & Stormwater Management",
        "Culverts & Box Drains",
        "Kerbs, Footpaths & Road Furniture",
        "Traffic Management & Signage",
        "Earthworks & Land Reclamation",
        "Utilities Relocation & Protection",
      ],
    },
    {
      id: "renovation-remodeling",
      title: "Renovation & Remodeling",
      slug: "renovation-remodeling",
      shortDesc: "Breathe new life into existing structures with our expert renovation and remodeling services.",
      fullDesc: "Whether it's a complete building overhaul, interior modernization, or structural upgrading, our renovation team brings expertise and care to every project. We understand the unique challenges of working with existing structures and pride ourselves on delivering transformations that exceed expectations.",
      icon: "RefreshCw",
      image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=75",
      category: "Building Enhancement",
      capabilities: [
        "Full Building Renovation",
        "Interior Remodeling & Modernization",
        "Structural Retrofitting & Strengthening",
        "Facade Restoration & Upgrades",
        "MEP System Upgrades",
        "Heritage & Conservation Works",
        "Space Reconfiguration",
        "Emergency Repair Services",
      ],
    },
    {
      id: "infrastructure-development",
      title: "Infrastructure Development",
      slug: "infrastructure-development",
      shortDesc: "Specialized in large-scale public infrastructure that serves communities and drives economic growth.",
      fullDesc: "We have extensive experience in developing critical infrastructure that serves communities and drives economic growth. From roads and bridges to utilities and public facilities, our infrastructure division delivers projects that meet international standards for quality, safety, and durability.",
      icon: "Landmark",
      image: "https://images.unsplash.com/photo-1429497419816-9ca5cfb4571a?auto=format&fit=crop&w=1200&q=75",
      category: "Public & Civil Works",
      capabilities: [
        "Bridge & Culvert Construction",
        "Water Supply & Distribution Systems",
        "Sewerage & Wastewater Treatment",
        "Public Facilities Development",
        "Utilities & Substation Works",
        "Telecommunication Infrastructure",
        "Coastal Protection Works",
        "Master Planning Support",
      ],
    },
    {
      id: "fire-protection",
      title: "Fire Protection",
      slug: "fire-protection",
      shortDesc: "Design, installation, and maintenance of complete fire detection and suppression systems.",
      fullDesc: "Our fire protection specialists design and install code-compliant fire alarm, sprinkler, hydrant, and suppression systems for commercial, industrial, and government facilities. We also provide periodic testing, servicing, and certification support to keep systems fully operational and compliant.",
      icon: "Flame",
      image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=75",
      category: "Building Services",
      capabilities: [
        "Fire Alarm & Detection Systems",
        "Sprinkler & Hose Reel Systems",
        "Hydrant & Wet Riser Systems",
        "Gas Suppression Systems",
        "Emergency Lighting & Signage",
        "Fire Doors & Compartmentation",
        "Periodic Testing & Certification",
        "Authority Submission Support",
      ],
    },
    {
      id: "green-building",
      title: "Green Building & Landscape",
      slug: "green-building",
      shortDesc: "Eco-friendly construction practices, sustainable materials, and professional landscaping.",
      fullDesc: "Integrating green technologies and energy-efficient materials into every build. We are committed to sustainable construction practices that reduce environmental impact while enhancing building performance and occupant comfort. Our landscape team completes the picture with softscape, hardscape, and irrigation works.",
      icon: "Leaf",
      image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=75",
      category: "Sustainable Solutions",
      capabilities: [
        "Energy-Efficient Building Design",
        "Sustainable Material Selection",
        "Solar & Renewable Energy Integration",
        "Rainwater Harvesting Systems",
        "Green Roof & Vertical Gardens",
        "Softscape & Hardscape Works",
        "Irrigation Systems",
        "Green Building Certification (GBI/LEED)",
      ],
    },
  ],
  industries: [
    { name: "Government", description: "Public sector projects including administrative buildings, civil infrastructure, and community facilities.", icon: "Landmark" },
    { name: "Commercial", description: "Office towers, retail centers, hotels, and mixed-use commercial developments.", icon: "Building" },
    { name: "Industrial", description: "Factories, warehouses, processing plants, and industrial facilities.", icon: "Factory" },
    { name: "Residential", description: "Luxury villas, landed properties, and high-end residential communities.", icon: "Home" },
    { name: "Hospitality", description: "Hotels, resorts, restaurants, and leisure facilities.", icon: "Hotel" },
    { name: "Healthcare", description: "Hospitals, clinics, medical centers, and healthcare facilities.", icon: "HeartPulse" },
    { name: "Education", description: "Schools, universities, training centers, and educational campuses.", icon: "GraduationCap" },
    { name: "Infrastructure", description: "Roads, bridges, drainage systems, and public utility infrastructure.", icon: "Route" },
    { name: "Oil & Gas", description: "Civil, structural, and maintenance support works for Brunei's energy sector.", icon: "Fuel" },
    { name: "Utilities", description: "Power, water, and telecommunications infrastructure and support facilities.", icon: "PlugZap" },
  ],
  products: [
    {
      name: "Hanchi Waterproofing",
      tagline: "Industrial-grade liquid membranes and sealants for complete moisture protection.",
      description: "Hanchi waterproofing solutions provide exceptional protection against water ingress for all types of structures. Our range includes liquid-applied membranes, cementitious coatings, and sealants suitable for roofs, basements, bathrooms, water tanks, and external walls.",
      applications: ["Roof Waterproofing", "Basement Waterproofing", "Bathroom & Wet Areas", "Water Tank Lining", "External Wall Coating", "Balcony & Terrace"],
      features: ["Excellent Adhesion", "UV Resistant", "Flexible & Crack-Bridging", "Easy Application", "Durable & Long-Lasting", "Environmentally Friendly"],
    },
    {
      name: "Hanchi Repair Solutions",
      tagline: "High-strength mortars and epoxy resins for reinforcing aging or damaged structures.",
      description: "Hanchi repair solutions are engineered for structural strengthening and restoration. Our high-performance mortars, epoxy resins, and protective coatings are designed to extend the service life of concrete and masonry structures.",
      applications: ["Concrete Crack Repair", "Structural Strengthening", "Spalling Repair", "Floor Hardening", "Anchor Grouting", "Protective Coating"],
      features: ["High Compressive Strength", "Low Shrinkage", "Excellent Bonding", "Fast Curing Options", "Freeze-Thaw Resistant", "Chemical Resistant"],
    },
  ],
  whyChooseUs: [
    { title: "Experienced Engineers", description: "Our team brings deep technical expertise and innovative solutions to every challenge.", icon: "Brain" },
    { title: "Quality Assurance", description: "Every project is executed with meticulous attention to detail and rigorous QA/QC processes.", icon: "Award" },
    { title: "Safety First", description: "Zero-harm philosophy with certified HSE practices on every site, every day.", icon: "ShieldCheck" },
    { title: "Certified Workforce", description: "Skilled, certified professionals with years of experience across diverse project types.", icon: "Users" },
    { title: "Modern Equipment", description: "A modern fleet of machinery and digital tools for efficient, precise delivery.", icon: "Truck" },
    { title: "On-Time Delivery", description: "We pride ourselves on completing projects on schedule without compromising quality.", icon: "Clock" },
    { title: "Government Contractor", description: "A trusted, registered contractor for Brunei government agencies and ministries.", icon: "Landmark" },
    { title: "Customer Satisfaction", description: "Building lasting relationships through transparency, communication, and results.", icon: "Heart" },
  ],
  safety: {
    commitment: "At Hasanur Jaya, safety is not just a policy — it's a core value that guides everything we do. We are committed to providing a safe and healthy working environment for all our employees, subcontractors, and the communities where we operate.",
    policies: [
      "Zero Harm Philosophy — every incident is preventable",
      "Strict compliance with Brunei's Workplace Safety and Health regulations",
      "Regular safety training and competency assessments for all personnel",
      "Comprehensive risk assessments before every project phase",
      "Continuous monitoring and improvement of safety performance",
    ],
    quality: "We maintain rigorous quality assurance processes throughout every project. Our quality management system ensures that all work meets or exceeds industry standards and client expectations.",
    environment: "We are dedicated to minimizing our environmental footprint through responsible resource management, waste reduction, and sustainable construction practices.",
    pillars: [
      { title: "HSE Policy", description: "A comprehensive health, safety, and environment policy governing every site and office.", icon: "ShieldCheck" },
      { title: "Quality Control", description: "Documented QA/QC procedures with hold points, checklists, and material approvals.", icon: "BadgeCheck" },
      { title: "Inspection & Testing", description: "Independent inspection and testing regimes covering structural, M&E, and finishing works.", icon: "Search" },
      { title: "Risk Assessment", description: "Job hazard analysis and method statements prepared before every work activity.", icon: "AlertTriangle" },
      { title: "Environmental Commitment", description: "Waste management, erosion control, and pollution prevention on every project.", icon: "Leaf" },
      { title: "Compliance", description: "Full compliance with Brunei WSH regulations, building codes, and authority requirements.", icon: "FileCheck" },
    ],
  },
  process: [
    { step: "Consultation", description: "We listen to your requirements, assess feasibility, and provide expert advice." },
    { step: "Planning", description: "Detailed scope, budget, schedule, and resource planning through HJSB EPPM." },
    { step: "Design", description: "Architectural and engineering design development with client collaboration." },
    { step: "Execution", description: "Construction delivered by certified teams with daily progress tracking." },
    { step: "Inspection", description: "Rigorous QA/QC inspections and testing at every hold point." },
    { step: "Completion", description: "Commissioning, authority approvals, documentation, and handover." },
    { step: "After Sales Support", description: "Defect liability support and long-term facility maintenance services." },
  ],
  projects: [
    {
      title: "Government Administrative Complex",
      slug: "government-administrative-complex",
      client: "Government of Brunei",
      location: "Bandar Seri Begawan",
      status: "Completed",
      value: "BND 18.5M",
      completed: "2024",
      scope: "Design & Build",
      description: "A four-storey administrative complex including offices, meeting facilities, surau, and landscaped grounds, delivered under a design-and-build contract.",
      image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=75",
    },
    {
      title: "Kuala Belait Commercial Centre",
      slug: "kuala-belait-commercial-centre",
      client: "Private Developer",
      location: "Kuala Belait",
      status: "Completed",
      value: "BND 12.2M",
      completed: "2023",
      scope: "Main Contract",
      description: "Mixed-use commercial centre with retail units, offices, and multi-storey parking, completed with full M&E and fire protection systems.",
      image: "https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&w=1200&q=75",
    },
    {
      title: "Gadong Luxury Residences",
      slug: "gadong-luxury-residences",
      client: "Commercial Client",
      location: "Gadong",
      status: "Ongoing",
      value: "BND 9.8M",
      completed: "Est. 2027",
      scope: "Design & Build",
      description: "A gated community of twelve luxury villas featuring bespoke architectural design, smart-home systems, and landscaped communal areas.",
      image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=75",
    },
    {
      title: "Seria Road & Drainage Upgrade",
      slug: "seria-road-drainage-upgrade",
      client: "Government of Brunei",
      location: "Seria",
      status: "Completed",
      value: "BND 7.4M",
      completed: "2024",
      scope: "Infrastructure",
      description: "Rehabilitation of 8.5 km of carriageway with new stormwater drainage, culverts, footpaths, street lighting, and road furniture.",
      image: "https://images.unsplash.com/photo-1508450859948-4e04fabaa4ea?auto=format&fit=crop&w=1200&q=75",
    },
    {
      title: "Rimba School Refurbishment",
      slug: "rimba-school-refurbishment",
      client: "Ministry of Education",
      location: "Bandar Seri Begawan",
      status: "Completed",
      value: "BND 3.1M",
      completed: "2025",
      scope: "Renovation",
      description: "Full refurbishment of classroom blocks, laboratories, and sports facilities including re-roofing, rewiring, and accessibility upgrades.",
      image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1200&q=75",
    },
    {
      title: "Industrial Warehouse Facility",
      slug: "industrial-warehouse-facility",
      client: "Private Client",
      location: "Muara",
      status: "Ongoing",
      value: "BND 5.6M",
      completed: "Est. 2026",
      scope: "Steel Structure",
      description: "Design, fabrication, and erection of a 12,000 m² steel-framed warehouse with office annex, loading bays, and fire protection systems.",
      image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=75",
    },
  ],
  clients: [
    "Ministry of Development",
    "Ministry of Education",
    "Public Works Department",
    "Brunei Shell Petroleum",
    "DST Group",
    "Baiduri Bank",
    "Times Square Group",
    "Consultant Partners",
  ],
  eppm: {
    title: "Enterprise Project Portfolio Management",
    name: "HJSB EPPM",
    description: "HJSB EPPM is the company's integrated digital platform for managing construction projects, maintenance services, procurement, finance, scheduling, workforce, and client collaboration — connecting employees, management, clients, consultants, and project teams in one secure system.",
    features: [
      { title: "Project Management", description: "Plan, track, and deliver projects with live dashboards.", icon: "KanbanSquare" },
      { title: "Planning & Scheduling", description: "Gantt schedules, milestones, and critical path tracking.", icon: "CalendarClock" },
      { title: "Tender & Bid", description: "Manage tenders, bids, and estimation in one place.", icon: "Gavel" },
      { title: "Maintenance Management", description: "Preventive and corrective maintenance programs.", icon: "Wrench" },
      { title: "Work Orders", description: "Dispatch, track, and close work orders digitally.", icon: "ClipboardList" },
      { title: "QR Asset Management", description: "QR-coded asset registers with full service history.", icon: "QrCode" },
      { title: "Inventory", description: "Stock control across warehouses and project sites.", icon: "Boxes" },
      { title: "Procurement", description: "Purchase requests, orders, and supplier management.", icon: "ShoppingCart" },
      { title: "Finance", description: "Budgets, claims, invoicing, and cost control.", icon: "Wallet" },
      { title: "Reports", description: "Real-time reporting and analytics across the portfolio.", icon: "BarChart3" },
      { title: "Customer Portal", description: "Clients view progress, documents, and requests.", icon: "UserCheck" },
      { title: "Technician Portal", description: "Field teams receive jobs and update status on site.", icon: "HardHat" },
    ],
  },
  gallery: [
    { src: "/images/gallery/img-1.jpg", alt: "Construction site", category: "Construction" },
    { src: "/images/gallery/img-2.jpg", alt: "Site progress", category: "Progress" },
    { src: "/images/gallery/img-3.jpg", alt: "Completed project", category: "Completed" },
    { src: "/images/gallery/img-4.jpg", alt: "Equipment", category: "Equipment" },
    { src: "/images/gallery/img-5.jpg", alt: "Workforce", category: "Workforce" },
    { src: "/images/gallery/img-6.jpg", alt: "Infrastructure", category: "Infrastructure" },
  ],
  navigation: [
    { label: "Home", href: "/" },
    { label: "About Us", href: "/about" },
    { label: "Services", href: "/services" },
    { label: "Industries", href: "/industries" },
    { label: "Projects", href: "/projects" },
    { label: "Safety & Quality", href: "/safety" },
    { label: "Careers", href: "/careers" },
    { label: "News", href: "/news" },
    { label: "Contact", href: "/contact" },
  ],
  careers: [
    {
      title: "Civil Engineer",
      type: "Full-Time",
      location: "Bandar Seri Begawan",
      department: "Engineering",
      description: "We are looking for an experienced Civil Engineer to join our project team.",
    },
    {
      title: "Safety Officer",
      type: "Full-Time",
      location: "Bandar Seri Begawan",
      department: "HSE",
      description: "Responsible for ensuring workplace safety compliance across all project sites.",
    },
    {
      title: "Project Manager",
      type: "Full-Time",
      location: "Bandar Seri Begawan",
      department: "Project Management",
      description: "Lead and manage construction projects from inception to completion.",
    },
  ],
};
